// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFettPL-pRkneI5vqLyWcD5yV8AqgHjLE',
    appId: '1:422515360756:web:e503dbf76dd3ff9b5c2fa1',
    messagingSenderId: '422515360756',
    projectId: 'haca-95e97',
    authDomain: 'haca-95e97.firebaseapp.com',
    storageBucket: 'haca-95e97.firebasestorage.app',
    measurementId: 'G-PFVBFB83MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWJcwcyEqBo--UXT4YSoKhX_ilS0Ga58',
    appId: '1:422515360756:android:3080815e430006665c2fa1',
    messagingSenderId: '422515360756',
    projectId: 'haca-95e97',
    storageBucket: 'haca-95e97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMAx4GuZWYLIEvoEywKcJ8ZOs23NDVGuA',
    appId: '1:422515360756:ios:0c53526eab9e6c235c2fa1',
    messagingSenderId: '422515360756',
    projectId: 'haca-95e97',
    storageBucket: 'haca-95e97.firebasestorage.app',
    iosBundleId: 'com.example.hacaReviewMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMAx4GuZWYLIEvoEywKcJ8ZOs23NDVGuA',
    appId: '1:422515360756:ios:0c53526eab9e6c235c2fa1',
    messagingSenderId: '422515360756',
    projectId: 'haca-95e97',
    storageBucket: 'haca-95e97.firebasestorage.app',
    iosBundleId: 'com.example.hacaReviewMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFettPL-pRkneI5vqLyWcD5yV8AqgHjLE',
    appId: '1:422515360756:web:f44165cc869343465c2fa1',
    messagingSenderId: '422515360756',
    projectId: 'haca-95e97',
    authDomain: 'haca-95e97.firebaseapp.com',
    storageBucket: 'haca-95e97.firebasestorage.app',
    measurementId: 'G-3PSY675NVT',
  );

}